[package]
name = "glowing-fiesta"
version = "0.1.0"
edition = "2024"

[dependencies]
csv = "1.3.1"
serde = { version = "1.0.219", features = ["derive"] }
rust_decimal = { version = "1.31.0", features = ["serde-str"] }
thiserror = "2.0.12"
anyhow = "1.0.98"
log = "0.4.27"
env_logger = "0.11.8"